config/routes.rb
Rails.application.routes.draw do
  get 'following/follow'

  devise_for :users
  resources :users
  resources :posts

  resources :users do
    member do
      get :following, :followers
    end
  end

  root "home#home"
  get '/about' => 'about#about'
  resources :relationships,only: [:create, :destroy]

  get '/posts/:id/success' => 'posts#success' 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes
  belongs_to :user
  validates :user_id,presence:true
  validates :question,presence:true
  validates :select1,presence:true
  validates :select2,presence:true
  validates :select3,presence:true
  validates :select4,presence:true
  validates :answer,presence:true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower ,class_name:"User"
  belongs_to :followed ,class_name:"User"
  validates :follower_id,presence:true
  validates :followed_id,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name,presence:true
  
  has_many :posts
  has_many :images
  has_many :likes ,dependent: :destroy
  has_many :active_relationships,
            class_name: "Relationship",
            foreign_key:"follower_id",
            dependent: :destroy
  has_many :passive_relationships,
            class_name: "Relationship",
            foreign_key:"followed_id",
            dependent: :destroy
  has_many :following,through: :active_relationships,source: :followed
  has_many :follower,through: :passive_relationships,source: :follower

  def follow(other_user)
    active_relationships(follower_id:other_user.id)
  end

  def unfollow(other_user)
    active_relationships(follower_id:other_user.id).destroy
  end

  def follow?(other_user)
    following.include?(other_user)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def about 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController
  def follow
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
		@users=User.all
		@user = @users.order("RAND()").limit(1).first #ActiveRecord::Relationで悩んだ件
	end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create
    @post=Post.new(id:params[:id],user_id:current_user.id,question:params[:question],select1:params[:select1],select2:params[:select2],select3:params[:select3],select4:[:select4],answer:params[:answer])
    if @post.save
      redirect_to("/posts")
    else
      render("posts/new")
    end
  end

  def index
    @posts=Post.all
  end

  def show
    @post=Post.find_by(id: params[:id])
  end

  def success
    @post=Post.find_by(id:params[:id],user_answer:params[:user_answer])
    if @post.answer==@post.user_answer
       render 'posts/success'
     else
       redirect_to('/posts/index')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nogizaka_helper.rb
module NogizakaHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/about/about.html.erb
<body>
<div class="main">
  <img class="mainimage" src="http://www.music-lounge.jp/v2/common/im/uf/news/20150223/nogizaka10.jpg">
  <h1>
    <span>推</span>し被りとつながろう
  </h1>
  <h2>
    オタクの、オタクによる、オタクのためのコミュニティ
  </h2>
  <p>
    オタク同士で繋がることができる、
  </p>
</div>
</body>
<script>
    $('.theme').each(function(){
  $(this).html($(this).text().replace(/([^\x00-\x80]|\w)/g, "<span class='letter'>$&</span>"));
});

anime.timeline({loop: true})
  .add({
    targets: '.theme .letter',
    scale: [4,1],
    opacity: [0,1],
    translateZ: 0,
    easing: "easeOutExpo",
    duration: 950,
    delay: function(el, i) {
      return 70*i;
    }
  }).add({
    targets: '.theme',
    opacity: 0,
    duration: 1000,
    easing: "easeOutExpo",
    delay: 1000
  });


$(function() {

  // 一旦hide()で隠してフェードインさせる
  $('.mainimage').hide().fadeIn('slow');

});
</script>

app/views/following/follow.html.erb
<body>
  <div class="users_index">
    <img class="back-image1" src="http://realsound.jp/wp-content/uploads/2017/05/20170416-keyaki.jpg">
    <div class="user-info">
      <img src="http://cdn.keyakizaka46.com/images/14/336/978bed423195be346fb180a71cc22/400_320_102400.jpg">
      <p>
        ユーザー名：日田豊隆
      </p>
      <p>
        推しグループ：欅坂
      </p>
      <p>
        推しメン：今泉佑唯
      </p>
    </div>
  </div>
</body>

app/views/home/home.html.erb
<div class="meet_btn">
  <p><%= link_to '出会う。',root_path%></p>
</div>


<div class="matching-home">
    <div class="user_matching_icon">
  <%= image_tag(@user.user_image)%>
  </div>
  <div class="self_introduce">
    <p class="self_name">名前:<%= @user.name %></p>
    <p class="member">推しメン:<%= @user.favorite%></p>
    <p class="group"> グループ:<%= @user.group%></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<li><%= link_to('/', {:class=>'header-logo'}) do%>
 <img src="https://pbs.twimg.com/media/DldAqsPU8AMTjhe.jpg">
</li>
<% end %>
<div class="header-menus">
  <ul>
   <li><%= link_to 'ログアウト',destroy_user_session_path,method: :delete%></li>
   <li>
     <%= link_to('ユーザーページ',user_path(current_user.id))%>
   </li>
   <li><%= link_to '投稿一覧','/posts',{:class=>'post_index'}%></li>
   <li><%= link_to '投稿',new_post_path,{:class=>'post'}%></li>
   <li><%= link_to 'tinderdaysとは',about_path,{:class=>'about'} %></li>
 </ul>
 </div>
<% else %>
<div class="header-menus">
 <ul>
   <li><%= link_to '新規登録',new_user_registration_path,{:class =>'sign_in' }%></li>
   <li><%= link_to 'ログイン',new_user_session_path,{:class=>'log_in'}%></li>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinderdays</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<body>
    <div class="user_index">
      <% @posts.each do |post| %>
      <div class="index_parent">
       <img src="https://i.pinimg.com/564x/a9/bd/3f/a9bd3faf83e4d2d7eb9eec5c979cf9e0.jpg">
        <p class="question">
          <%=link_to post_path(post.id) do %>
         問題：<%= post.question %>
          <% end %>
        </p>
     </div>
    <% end %>
  </div>
</body>

app/views/posts/new.html.erb
<body>
  <div class="quiz">
    <div class="quiz-form">
    <p>問題</p>
    <%= form_tag("/posts",method: :"post") do %>
    <textarea class="question" name="question"></textarea>
         <input class="ans1" name="select1" placeholder="解答１">
         <input class="ans2" name="select2" placeholder="解答２">
         <input class="ans3" name="select3" placeholder="解答３">
         <input class="ans4" name="select4" placeholder="解答４">
         <input class="answer" name="answer" type="number" placeholder="answer">
         <div class="send">
           <input class="create" type="submit" value="作成">
         </div>
       </div>
    <% end %>
  </div>
</body>

app/views/posts/show.html.erb
  <div class="quiz_fujisawa">
    <div class="question_fujisawa">
     <h1>問題</h1>
    </div>
    <p class="question_content_fujisawa">
      <%= @post.question %>
    </p>
    <%= form_for("/posts/:id/success") do %>
    <div class="choices_fujisawa">
    <input class="first fujisawa" name="user_answer" type="button" value="<%=@post.select1%>"><br>
    <input class="second fujisawa" name="user_answer" type="button" value="<%=@post.select2%>"><br>
    <input class="third fujisawa" name="user_answer" type="button" value="<%=@post.select3%>"><br>
    <input class="fourth fujisawa" name="user_answer" type="button" value="<%= @post.select4%>">
    <% end %>
    </div>
  </div>

app/views/posts/success.html.erb
<body>
<div class="true">
  <p id="true">
  正解！！
  </p>
  <% link_to (posts_path) do %>
  <div type="button" class="back">
    ホームに戻る
  </div>
 <% end %>
</div>
</body>

<script>
  $(function() {
    $('.back').hide().fadeIn(1000);
});


$(function() {
    $('#true').hide().fadeIn(3000);
});
</script>

app/views/users/show.html.erb
<body>
  <div class="user">
  <div class="user_self_intr">
    <div class="user_image_icon">
      <img src="<%= current_user.user_image %>">
    </div>
    <div class="user_intr_content">
     <p>ユーザー名：<%= current_user.name%></p>
     <p>推しグループ：<%= current_user.group%></p>
     <p>推しメン：<%= current_user.favorite%></p>
   </div>
  </div>
 </div>
</body>